[package]
name = "muxui"
version = "0.1.0"
edition = "2024"

[dependencies]
gss = { git = "https://github.com/MarcosAndradeV/GSS", version = "0.1.0", features = ["interning"] }
raylib = { git = "https://github.com/MarcosAndradeV/raylib-rs", version = "0.1.0" }

# cargo run --example example
[[example]]
name = "example"
path = "src/example/main.rs"
