[package]
name = "muxapp"
version = "0.1.0"
edition = "2024"

[features]
default = ["point-and-click"]
point-and-click = ["dep:muxengine"]

[dependencies]
notify = "8.2.0"
muxui = { path = "../muxui", version = "0.1.0" }
muxutils = { path = "../muxutils", version = "0.1.0" }
muxengine = { path = "../muxengine", version = "0.1.0", optional = true }

